Create Generic disbot.js
timm3/ASSDIC pull request #18
Opened 2021-03-13 19:29 UTC by aelagrassa

This is a generic disbot file that has many of the previous media/audio files removed. It's only real feature is using YTDL and showing a few examples of responding to text and playing a single mp3 file [horn].

2021-04-30 06:26 UTC, timm3 requested changes
This stripped down bot is a good start, and just needs to be stripped down a little further to be a base/starter/generic bot.
Please remove the dead code and consolidate the handling of `/join` and `!stop` commands.

2021-04-30 06:26 UTC, timm3 commented on disbot.js
> +
```suggestion
```

2021-04-30 06:26 UTC, timm3 commented on disbot.js
> +  }
```suggestion
```

2021-04-30 06:26 UTC, timm3 commented on disbot.js
> +
```suggestion
```

2021-04-30 06:26 UTC, timm3 commented on disbot.js
> +          case '/join':
```suggestion
```

2021-04-30 06:26 UTC, timm3 commented on disbot.js
> +          case '/join':
`/join` is handled in the other message handler, and should not cause the bot to say that the bot is stopping

2021-04-30 06:26 UTC, timm3 commented on disbot.js
> +            break;
```suggestion
```

I'd handle the `!stop` command in just one location, and move `message.reply('Stopping boss!');` to the other handler for this special command

2021-12-10 00:51 UTC, aelagrassa commented
Closing due to noobery

2021-12-10 00:51 UTC, closed without merging